package com.launchcode.studio.cheesemvc.models;


import javax.annotation.Generated;
import javax.persistence.*;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import java.util.List;

@Entity
@Table(name="cheeses") //Default behavior is the name of the class
public class Cheese {
  //private static int nextCheeseID = 0;

  @Id //Signifies that this field is the primary key
  @GeneratedValue //auto generated by the database
  //@Column(name="CHEESE_ID") - This annotation allows you to specify the name of the column on the DB
  private int id;

  @NotNull
  @Size(min=3, max=15, message = "Cheese name must be between 3 and 15 characters")
  private String name;

  @NotNull
  @Size(min=1, message="Description must not be empty")
  private String description;

  @ManyToOne
  private Category category;

  @ManyToMany(mappedBy = "cheeses")
  private List<Menu> menus;

  public int getCheeseID() {
    return id;
  }

  public int getId() {
    return id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public String getName() {
    return name;
  }

  public String getDescription() {
    return description;
  }

  public void setName(String name) {
    this.name = name;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Category getCategory() {
    return category;
  }

  public void setCategory(Category category) {
    this.category = category;
  }
}
